version: "3.8"
services:
  postgres:
    image: postgres:11.10-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-goappcore}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-goappcore}
      - POSTGRES_DB=${POSTGRES_DB:-goappcore}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  mock_users_api:
    image: mockserver/mockserver:mockserver-snapshot
    ports:
      - 1180:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mock-users-api-config.json
    volumes:
      - type: bind
        source: ./config
        target: /config
